spring:
  shardingsphere:
    datasource:
      names: master,slave1,slave2
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.200.174:3306/db_user
        username: root
        password: 123456
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.200.174:3307/db_user
        username: root
        password: 123456
      slave2:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.200.174:3308/db_user
        username: root
        password: 123456
    rules:
      readwrite-splitting:
        dataSources:
          <data-source-name> (+): # 读写分离逻辑数据源名称
            static-strategy: # 读写分离类型
              write-data-source-name: master # 写库数据源名称
              read-data-source-names: slave1,slave2
          loadBalancerName: random
        loadBalancers:
          random:
            type: ROUND_ROBIN
            props:
              default: 0
              sql-show: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
