spring:
  shardingsphere:
    datasource:
      names: master,slave1,slave2
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.200.174:3306/t_user
        username: root
        password: 123456
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.200.174:3307/t_user
        username: root
        password: 123456
      slave2:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.200.174:3308/t_user
        username: root
        password: 123456
    mode:
      type: Memory
    rules:
      readwrite-splitting:
        data-sources:
          <data-source-name> (+): myds # \u8BFB\u5199\u5206\u79BB\u903B\u8F91\u6570\u636E\u6E90\u540D\u79F0
            static-strategy: static #\u8BFB\u5199\u5206\u79BB\u7C7B\u578B
              write-data-source-name: master # \u5199\u5E93\u6570\u636E\u6E90\u540D\u79F0
              read-data-source-names: slave1,slave2
              loadBalancerName: alg_round # \u8D1F\u8F7D\u5747\u8861\u7B97\u6CD5\u540D\u79F0
    props:
      sql-show: true

