spring:
  shardingsphere:
    datasource:
      names: server-user,server-order
      server-user:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.200.174:3301/db_user
        username: root
        password: 123456
      server-order:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.200.174:3302/db_order
        username: root
        password: 123456
    props:
      sql-show: true
    rules:
      SHARDING
      tables: # 数据分片规则配置
        <logic-table-name> (+): t_user,t_order # 逻辑表名称
          actualDataNodes (?):  # 由数据源名 + 表名组成（参考 Inline 语法规则）
          databaseStrategy (?): # 分库策略，缺省表示使用默认分库策略，以下的分片策略只能选其一
            standard: # 用于单分片键的标准分片场景
              shardingColumn: # 分片列名称
              shardingAlgorithmName: # 分片算法名称
            complex: # 用于多分片键的复合分片场景
              shardingColumns: # 分片列名称，多个列以逗号分隔
              shardingAlgorithmName: # 分片算法名称
            hint: # Hint 分片策略
              shardingAlgorithmName: # 分片算法名称
            none: # 不分片
          tableStrategy: # 分表策略，同分库策略
          keyGenerateStrategy: # 分布式序列策略
            column: # 自增列名称，缺省表示不使用自增主键生成器
            keyGeneratorName: # 分布式序列算法名称
          auditStrategy: # 分片审计策略
            auditorNames: # 分片审计算法名称
              - <auditor-name>
              - <auditor-name>
            allowHintDisable: true # 是否禁用分片审计hint
      autoTables: # 自动分片表规则配置
        t_order_auto: # 逻辑表名称
          actualDataSources (?): # 数据源名称
          shardingStrategy: # 切分策略
            standard: # 用于单分片键的标准分片场景
              shardingColumn: # 分片列名称
              shardingAlgorithmName: # 自动分片算法名称
      bindingTables (+): # 绑定表规则列表
        - <logic_table_name_1, logic_table_name_2, ...>
        - <logic_table_name_1, logic_table_name_2, ...>
      broadcastTables (+): # 广播表规则列表
        - <table-name>
        - <table-name>
      defaultDatabaseStrategy: # 默认数据库分片策略
      defaultTableStrategy: # 默认表分片策略
      defaultKeyGenerateStrategy: # 默认的分布式序列策略
      defaultShardingColumn: # 默认分片列名称
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
